-- Base transacional da API cadastral: vigência da UC, histórico geométrico, eventos cadastrais,
-- idempotência e controle de migrações. Complementa o schema criado por init_db.sql.

ALTER TABLE public.uc
    ADD COLUMN IF NOT EXISTS situacao VARCHAR(10) NOT NULL DEFAULT 'ATIVA',
    ADD COLUMN IF NOT EXISTS dt_inicio_vigencia DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS dt_fim_vigencia DATE,
    ADD COLUMN IF NOT EXISTS versao_registro BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(255),
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_uc_situacao' AND conrelid = 'public.uc'::regclass
    ) THEN
        ALTER TABLE public.uc
            ADD CONSTRAINT ck_uc_situacao CHECK (situacao IN ('ATIVA', 'EXTINTA'));
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_uc_uc_id
    ON public.uc (uc_id) WHERE uc_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_uc_cd_cnuc
    ON public.uc (cd_cnuc) WHERE cd_cnuc IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.uc_geometry_version (
    id_geometry_version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_uc BIGINT NOT NULL REFERENCES public.uc(id_uc) ON UPDATE CASCADE ON DELETE RESTRICT,
    numero_versao BIGINT NOT NULL,
    geom geometry(Geometry, 4674) NOT NULL,
    fl_ativa BOOLEAN NOT NULL DEFAULT TRUE,
    dt_inicio_vigencia DATE NOT NULL DEFAULT CURRENT_DATE,
    dt_fim_vigencia DATE,
    motivo TEXT NOT NULL,
    fonte VARCHAR(255) NOT NULL,
    ator VARCHAR(255) NOT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_uc_geometry_version UNIQUE (id_uc, numero_versao),
    CONSTRAINT ck_uc_geometry_version_periodo CHECK (
        dt_fim_vigencia IS NULL OR dt_fim_vigencia >= dt_inicio_vigencia
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_uc_geometry_version_ativa
    ON public.uc_geometry_version (id_uc) WHERE fl_ativa = TRUE;

CREATE INDEX IF NOT EXISTS idx_uc_geometry_version_geom
    ON public.uc_geometry_version USING GIST (geom);

CREATE TABLE IF NOT EXISTS public.cadastral_event (
    event_id UUID PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    reason TEXT NOT NULL,
    source VARCHAR(255) NOT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    previous_state JSONB,
    new_state JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cadastral_event_entity
    ON public.cadastral_event (entity_type, entity_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.outbox_event (
    event_id UUID PRIMARY KEY,
    topic VARCHAR(150) NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    last_error TEXT,
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_outbox_pending
    ON public.outbox_event (available_at, created_at) WHERE status = 'PENDING';

CREATE TABLE IF NOT EXISTS public.api_idempotency (
    idempotency_key VARCHAR(255) PRIMARY KEY,
    operation VARCHAR(100) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    response_status INTEGER NOT NULL,
    response_body JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.api_schema_migration (
    version VARCHAR(100) PRIMARY KEY,
    checksum CHAR(64) NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
