-- Contas, sessão e auditoria de login para o módulo de autenticação (Fase 2).
-- Sessão opaca em tabela: o token em claro nunca é persistido, apenas seu hash SHA-256.
-- Ver frontend-protected-areas-sc/docs/SDD.md, seção 2, para o desenho completo.

CREATE TABLE IF NOT EXISTS public.app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(120) NOT NULL,
    nome            VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    ativo           BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_por      BIGINT       REFERENCES public.app_user(id),
    criado_em       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_app_user_role CHECK (role IN ('admin', 'operador'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_app_user_username ON public.app_user (username);

-- Sessão opaca: só o hash do token vive no banco; o token em claro só existe no cookie
-- httpOnly do navegador. Revogar é um UPDATE, sem depender de expiração de JWT stateless.
CREATE TABLE IF NOT EXISTS public.app_session (
    token_hash      CHAR(64) PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES public.app_user(id),
    criado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_em       TIMESTAMPTZ NOT NULL,
    revogado_em     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_app_session_user ON public.app_session (user_id);

-- Toda tentativa de login (sucesso ou falha) fica registrada por username, não por conta
-- resolvida, para que o bloqueio por força bruta também cubra usernames inexistentes.
CREATE TABLE IF NOT EXISTS public.login_attempt (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(120) NOT NULL,
    sucesso       BOOLEAN NOT NULL,
    ip_origem     INET,
    criado_em     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_attempt_username_time
    ON public.login_attempt (username, criado_em);
