-- Modo eventos: ampliação temporária do nó de serviço para oficinas, operada pelo painel.
-- O estado fica no banco porque a própria API para durante a troca de tamanho da máquina.

CREATE TABLE IF NOT EXISTS public.event_mode_event (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                   VARCHAR(80)  NOT NULL,
    status                 VARCHAR(20)  NOT NULL,
    db_login               VARCHAR(63)  NOT NULL,
    starts_at              TIMESTAMPTZ  NOT NULL,
    auto_return_at         TIMESTAMPTZ  NOT NULL,
    activated_at           TIMESTAMPTZ,
    deactivate_allowed_at  TIMESTAMPTZ,
    finished_at            TIMESTAMPTZ,
    execution_id           VARCHAR(64),
    current_step           VARCHAR(128),
    failure_message        VARCHAR(1000),
    requested_by           BIGINT       NOT NULL REFERENCES public.app_user(id),
    idempotency_key        VARCHAR(200),
    version                INTEGER      NOT NULL DEFAULT 1,
    criado_em              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_event_mode_status CHECK (
        status IN ('agendado', 'ativando', 'ativo', 'desativando', 'encerrado', 'cancelado', 'falhou')
    ),
    CONSTRAINT ck_event_mode_login CHECK (db_login ~ '^ws_[a-z0-9_]+$'),
    CONSTRAINT ck_event_mode_return CHECK (auto_return_at > starts_at)
);

-- Um único evento aberto por vez: o segundo pedido falha no banco mesmo sob concorrência.
CREATE UNIQUE INDEX IF NOT EXISTS uq_event_mode_open
    ON public.event_mode_event ((true))
    WHERE status IN ('agendado', 'ativando', 'ativo', 'desativando');

CREATE UNIQUE INDEX IF NOT EXISTS uq_event_mode_idempotency
    ON public.event_mode_event (idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- Trilha de quem fez o quê; ações automáticas (laço da API, automação) ficam com usuário nulo.
CREATE TABLE IF NOT EXISTS public.event_mode_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT       NOT NULL REFERENCES public.event_mode_event(id),
    user_id     BIGINT       REFERENCES public.app_user(id),
    acao        VARCHAR(40)  NOT NULL,
    detalhe     VARCHAR(1000),
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_mode_audit_event ON public.event_mode_audit (event_id);

-- A API escreve o estado do evento e a auditoria. A concessão fica aqui, e não no grants.sql da
-- infraestrutura, para o deploy automático não depender de um passo manual. Bancos locais sem o
-- papel pa_api apenas pulam este bloco.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pa_api') THEN
        GRANT SELECT, INSERT, UPDATE ON public.event_mode_event TO pa_api;
        GRANT SELECT, INSERT ON public.event_mode_audit TO pa_api;
    END IF;
END
$$;
